["Artifactory Configs"]
	#How many levels by default you need to have to start the attunement process. Default: 35
	# Default: 30
	# Range: > 0
	xpLevelThreshold = 30
	#How many levels by default are consumed to attune an item.
	# Default: 20
	# Range: > 0
	xpLevelsConsumed = 20
	#These effects are applied to a player who is wearing a restricted item in one of the armor slots.
	#The format is "effect/level;effect/level;etc" so if you wanted a player to be slowed at
	#level 3 and poisoned at level 1 you would put "minecraft:slowness/3;minecraft:poison/1".
	wearRestrictedEffects = "minecraft:slowness/4"
	#These effects are applied to a player who is wearing a restricted item in one of the armor slots.
	#The format is "effect/level;effect/level;etc" so if you wanted a player to be slowed and poisoned
	#you would put "minecraft:slowness/3;minecraft:poison/1".
	holdingOtherPlayersItemEffects = "minecraft:slowness/4;minecraft:poison/2"
	#If an attunement item has not been identified .
	"Show Unidentified Percentage" = true

[Keybinds]
	#Controls if a player can open the manage attunements screen from a keybind.
	#If true the player can assign a keybind to the manage attunements screen and open it anywhere.
	#If false it will not ope when the keybind is assigned and pressed.
	"Can Open Manage Attunements Screen From Keybind" = true
