#修饰系统配置
[modifiers]
	#是否启用饰品修饰系统
	enabled = true

#铁砧重铸系统配置
[anvilRecast]
	#重铸所需经验等级
	# Default: 3
	# Range: 1 ~ 100
	expCost = 3
	#重铸消耗的材料数量
	# Default: 1
	# Range: 1 ~ 64
	materialCost = 1

[mana]
	#默认最大魔力值
	# Default: 100.0
	# Range: 10.0 ~ 10000.0
	defaultMaxMana = 100.0
	#魔力恢复冷却时间（以tick为单位，20 tick = 1秒）
	# Default: 20
	# Range: 0 ~ 20000
	manaRegenCooldown = 20
	#每次恢复的魔力量
	# Default: 3.0
	# Range: 1.0 ~ 10000.0
	manaRegenRate = 3.0
	#魔力恢复间隔（以tick为单位）
	# Default: 20
	# Range: 1 ~ 20000
	manaRegenInterval = 20
	#创造模式每tick恢复的魔力量
	# Default: 5
	# Range: 1 ~ 10000
	creativeRegenRate = 5

[arcingOrb]
	#移动速度增益倍率
	# Default: 0.25
	# Range: 0.0 ~ 1000.0
	speedBoost = 0.25
	#每tick的充能速率和魔力消耗
	# Default: 0.5
	# Range: 0.1 ~ 5000.0
	chargeRate = 0.5
	#最小充能需求
	# Default: 5.0
	# Range: 1.0 ~ 5000.0
	minCharge = 5.0
	#最大充能值
	# Default: 100.0
	# Range: 10.0 ~ 10000.0
	maxCharge = 100.0
	#伤害系数
	# Default: 0.133
	# Range: 0.01 ~ 100.0
	damageMultiplier = 0.133
	#闪避技能的位移距离
	# Default: 5.0
	# Range: 1.0 ~ 2000.0
	dashDistance = 5.0
	#闪避技能冷却时间（单位：tick）
	# Default: 20
	# Range: 1 ~ 20000
	dashCooldown = 20
	#闪避技能消耗的魔力值
	# Default: 10.0
	# Range: 1.0 ~ 10000.0
	dashManaCost = 10.0
	#跳跃时闪避的额外推力系数
	# Default: 0.3
	# Range: 0.0 ~ 1.0
	dashJumpBoost = 0.3

[dragonsEye]
	#最大渲染方块数量
	#更大的数值可能会影响性能
	#范围: 50-10000
	# Default: 200
	# Range: 50 ~ 10000
	max_render_blocks = 200
	#渲染范围（以方块为单位）
	#这个值会被平方来计算实际范围
	#默认值12表示12*12的范围
	#范围: 1-128
	# Default: 12
	# Range: 1 ~ 128
	render_range = 12

	[dragonsEye.valuable]
		#贵重矿物组 - 在这里添加要探测的额外贵重矿石
		#添加方式示例：
		#["minecraft:ancient_debris", "create:zinc_ore", "thermal:silver_ore"]
		#或者每个矿石单独一行：
		#[
		#    "minecraft:ancient_debris",
		#    "create:zinc_ore",
		#    "thermal:silver_ore"
		#]
		ores = []

	[dragonsEye.common]
		#常见矿物组 - 在这里添加要探测的额外普通矿石
		#添加方式示例：
		#["create:copper_ore", "thermal:tin_ore", "mekanism:osmium_ore"]
		#注意：每个矿石ID之间需要用逗号分隔，最后一个不需要加逗号
		ores = []

	[dragonsEye.redstone]
		#红石矿物组 - 在这里添加要探测的额外红石类矿石
		#添加方式示例：
		#["thermal:cinnabar_ore", "projectred:electrotine_ore"]
		#注意：矿石ID格式必须是 模组id:方块id
		ores = []

[enderCrown]
	#末影人跟随范围
	# Default: 16.0
	# Range: 8.0 ~ 32.0
	followRange = 16.0
	#伤害免疫触发概率
	# Default: 0.02
	# Range: 0.0 ~ 1.0
	immunityChance = 0.02
	#传送范围
	# Default: 32.0
	# Range: 8.0 ~ 64.0
	teleportRange = 32.0
	#是否启用水伤害
	waterDamageEnabled = false

[faelisClaw]
	#攻击力增益百分比
	# Default: 0.25
	# Range: 0.0 ~ 100.0
	damageBoost = 0.25
	#流血效果触发概率
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	bleedChance = 0.25
	#流血效果持续时间(tick)
	# Default: 300
	# Range: 20 ~ 12000
	bleedDuration = 300
	#普通状态下流血持续时间倍率
	# Default: 0.3333333333333333
	# Range: 0.1 ~ 100.0
	normalDurationMultiplier = 0.3333333333333333

[manaCandy]
	#魔力糖果恢复的魔力值
	# Default: 50
	# Range: 1 ~ 20000
	restore = 50

[manaCrystal]
	#魔力水晶增加的魔力上限值
	# Default: 10
	# Range: 1 ~ 50000
	maxIncrease = 10

[manaReagent]
	#魔力试剂减少的魔力上限值
	# Default: 10
	# Range: 1 ~ 50000
	maxDecrease = 10

[poisonStone]
	#毒石触发中毒效果的概率
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	chance = 0.2
	#中毒效果持续时间(tick)
	# Default: 60
	# Range: 20 ~ 40000
	duration = 60
	#中毒效果等级
	# Default: 0
	# Range: 0 ~ 255
	amplifier = 0
	#对中毒目标的伤害倍率
	# Default: 2.0
	# Range: 1.0 ~ 500.0
	damageMultiplier = 2.0

[polarizedStone]
	#物品吸引范围
	# Default: 12.0
	# Range: 4.0 ~ 64.0
	attractionRange = 12.0
	#物品吸引速度
	# Default: 0.5
	# Range: 0.1 ~ 10.0
	attractionSpeed = 0.5
	#弹射物防御范围
	# Default: 2.0
	# Range: 1.0 ~ 10.0
	deflectionRange = 2.0
	#每秒防御消耗魔力/秒
	# Default: 5.0
	# Range: 0.0 ~ 5000.0
	deflectionManaCost = 5.0

[shield]
	#完全免伤所需的伤害计数
	# Default: 3
	# Range: 1 ~ 100
	maxDamageCount = 3
	#基础伤害减免百分比
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	damageReduction = 0.2
	#爆炸伤害减免系数
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	explosionReduction = 0.25

[greaterInertiaStone]
	#击退抗性增加值
	# Default: 0.4
	# Range: 0.0 ~ 1.0
	knockbackResistance = 0.4
	#移动速度增加百分比
	# Default: 1.5
	# Range: -1.0 ~ 30.0
	movementSpeed = 1.5
	#跳跃高度提升值
	# Default: 0.4
	# Range: 0.0 ~ 100.0
	jumpBoost = 0.4
	#摔落伤害减免系数(0.25表示减免75%)
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	fallReduction = 0.25
	#跨步高度增加值
	# Default: 0.4
	# Range: -1.0 ~ 10.0
	stepHeight = 0.4

[witherRing]
	#凋零效果触发概率
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	chance = 0.2
	#凋零效果持续时间(tick)
	# Default: 100
	# Range: 20 ~ 6000
	duration = 100
	#凋零效果等级
	# Default: 0
	# Range: 0 ~ 4
	amplifier = 0

[dragon]
	#攻击伤害提升百分比
	# Default: 0.5
	# Range: -1.0 ~ 50.0
	attackDamageBoost = 0.5
	#最大生命值提升百分比
	# Default: 0.25
	# Range: -1.0 ~ 50.0
	maxHealthBoost = 0.25
	#盔甲韧性增加百分比
	# Default: 0.5
	# Range: -1.0 ~ 20.0
	armorToughness = 0.5
	#飞行速度倍率
	# Default: 0.3
	# Range: -1.0 ~ 2.0
	flightSpeed = 0.3
	#魔力值加成
	# Default: 300.0
	# Range: 0.0 ~ 10000.0
	manaBonus = 300.0
	#每秒飞行消耗魔力值
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	flightManaCost = 5.0
	#魔力检查间隔(tick)
	# Default: 20.0
	# Range: 1.0 ~ 200.0
	manaCheckInterval = 20.0
	#每秒龙息消耗魔力
	# Default: 5.0
	# Range: 0.0 ~ 5000.0
	breathManaCost = 5.0
	#龙息基础伤害
	# Default: 4.0
	# Range: 0.0 ~ 100.0
	BreathBaseDamage = 4.0
	#龙息最小伤害
	# Default: 2.0
	# Range: 0.0 ~ 100.0
	BreathMinDamage = 2.0
	#龙息伤害衰减率
	# Default: 0.7
	# Range: 0.0 ~ 1.0
	BreathDecayRate = 0.7
	#龙族体型缩放 1 为正常体型
	# Default: 1.2
	# Range: 0.1 ~ 10.0
	scale = 1.2

[dwarves]
	#攻击速度修改值(负值降低,正值提升)
	# Default: -0.25
	# Range: -1.0 ~ 100.0
	attackSpeed = -0.25
	#攻击伤害修改值
	# Default: 0.25
	# Range: -1.0 ~ 200.0
	attackDamage = 0.25
	#最大生命值修改值
	# Default: -0.3
	# Range: -1.0 ~ 200.0
	maxHealth = -0.3
	#护甲韧性修改值
	# Default: 0.25
	# Range: -1.0 ~ 200.0
	armorToughness = 0.25
	#击退抗性修改值
	# Default: 0.2
	# Range: -1.0 ~ 1.0
	knockbackResistance = 0.2
	#移动速度修改值
	# Default: -0.25
	# Range: -1.0 ~ 100.0
	movementSpeed = -0.25
	#矮人族体型缩放 1 为正常体型
	# Default: 0.75
	# Range: 0.1 ~ 10.0
	scale = 0.75

[elves]
	#基础攻击速度修改值
	# Default: 0.3
	# Range: -1.0 ~ 20.0
	attackSpeed = 0.3
	#基础攻击伤害修改值
	# Default: -0.25
	# Range: -1.0 ~ 20.0
	attackDamage = -0.25
	#基础移动速度修改值
	# Default: 0.1
	# Range: -1.0 ~ 20.0
	movementSpeed = 0.1
	#森林中额外攻击速度加成
	# Default: 0.15
	# Range: -1.0 ~ 10.0
	forestAttackSpeed = 0.15
	#森林中额外移动速度加成
	# Default: 0.15
	# Range: -1.0 ~ 10.0
	forestMovementSpeed = 0.15
	#精灵效果魔力值增加量
	# Default: 100.0
	# Range: 0.0 ~ 10000.0
	manaBonus = 100.0
	#潜行时弓箭伤害增加倍率
	# Default: 1.5
	# Range: 1.0 ~ 50.0
	bowDamageBoost = 1.5
	#精灵族体型缩放 1 为正常体型
	# Default: 0.5
	# Range: 0.1 ~ 10.0
	scale = 0.5

[faeles]
	#基础攻击伤害修改值
	# Default: -0.25
	# Range: -1.0 ~ 1.0
	attackDamage = -0.25
	#攻击速度修改值
	# Default: 0.15
	# Range: -1.0 ~ 2.0
	attackSpeed = 0.15
	#最大生命值修改值
	# Default: -0.25
	# Range: -1.0 ~ 1.0
	maxHealth = -0.25
	#护甲韧性修改值
	# Default: -0.15
	# Range: -1.0 ~ 100.0
	armorToughness = -0.15
	#移动速度修改值
	# Default: 0.15
	# Range: -1.0 ~ 200.0
	movementSpeed = 0.15
	#幸运值增加
	# Default: 2.0
	# Range: -100.0 ~ 100.0
	luck = 2.0
	#游泳速度修改值
	# Default: 0.3
	# Range: -1.0 ~ 200.0
	swimSpeed = 0.3
	#跳跃高度修改值
	# Default: 0.6
	# Range: -1.0 ~ 200.0
	jumpStrength = 0.6
	#空手伤害增加值
	# Default: 6.0
	# Range: -100.0 ~ 2000.0
	unarmedDamage = 6.0
	#跨步高度增加值
	# Default: 0.4
	# Range: 0.0 ~ 100.0
	stepHeight = 0.4
	#交互距离修改值
	# Default: -0.1
	# Range: -1.0 ~ 0.5
	reach = -0.1
	#每件非皮革护甲的速度惩罚
	# Default: -0.04
	# Range: -1.0 ~ 0.0
	armorSpeedPenalty = -0.04
	#魔力值增加量
	# Default: 25.0
	# Range: 0.0 ~ 10000.0
	manaBonus = 25.0
	#猫猫效果是否允许攀爬墙壁
	wallClimb = true
	#猫猫效果爬墙速度（原版梯子速度约为0.11）
	# Default: 0.11
	# Range: 0.05 ~ 0.3
	climbSpeed = 0.11
	#猫猫效果爬墙时的水平移动阻力
	# Default: 0.7
	# Range: 0.5 ~ 1.0
	climbHorizontalDrag = 0.7
	#猫族体型缩放 1 为正常体型
	# Default: 0.85
	# Range: 0.1 ~ 10.0
	scale = 0.85

[fairyDew]
	#攻击伤害修改值
	# Default: -0.75
	# Range: -1.0 ~ 100.0
	attackDamage = -0.75
	#最大生命值修改值
	# Default: -0.6
	# Range: -1.0 ~ 100.0
	maxHealth = -0.6
	#护甲值修改值
	# Default: -0.5
	# Range: -1.0 ~ 100.0
	armor = -0.5
	#护甲韧性修改值
	# Default: -0.25
	# Range: -1.0 ~ 100.0
	armorToughness = -0.25
	#移动速度修改值
	# Default: -0.25
	# Range: -1.0 ~ 100.0
	movementSpeed = -0.25
	#游泳速度修改值
	# Default: -0.25
	# Range: -1.0 ~ 100.0
	swimSpeed = -0.25
	#交互距离修改值
	# Default: -0.35
	# Range: -1.0 ~ 100.0
	reach = -0.35
	#跨步高度增加值
	# Default: 0.4
	# Range: -1.0 ~ 100.0
	stepHeight = 0.4
	#飞行速度倍率
	# Default: 0.3
	# Range: -1.0 ~ 2.0
	flightSpeed = 0.3
	#魔力值增加量
	# Default: 400.0
	# Range: 0.0 ~ 20000.0
	manaBonus = 400.0
	#跳跃高度修改值
	# Default: -0.25
	# Range: -1.0 ~ 200.0
	jumpStrength = -0.25
	#精灵露效果是否允许攀爬墙壁
	wallClimb = true
	#精灵露效果爬墙速度（原版梯子速度约为0.11）
	# Default: 0.11
	# Range: 0.05 ~ 0.3
	climbSpeed = 0.11
	#精灵露效果爬墙时的水平移动阻力
	# Default: 0.7
	# Range: 0.5 ~ 1.0
	climbHorizontalDrag = 0.7
	#仙女族体型缩放 1 为正常体型
	# Default: 0.25
	# Range: 0.1 ~ 10.0
	scale = 0.25

[goblin]
	#攻击伤害修改值
	# Default: -0.5
	# Range: -1.0 ~ 0.0
	attackDamage = -0.5
	#最大生命值修改值
	# Default: -0.4
	# Range: -1.0 ~ 0.0
	maxHealth = -0.4
	#移动速度修改值
	# Default: 0.2
	# Range: -1.0 ~ 1.0
	movementSpeed = 0.2
	#幸运值增加
	# Default: 1.0
	# Range: -100.0 ~ 100.0
	luck = 1.0
	#游泳速度修改值
	# Default: 0.1
	# Range: -1.0 ~ 100.0
	swimSpeed = 0.1
	#跨步高度增加值
	# Default: 0.4
	# Range: -1.0 ~ 100.0
	stepHeight = 0.4
	#魔力值修改量
	# Default: -25.0
	# Range: -10000.0 ~ 10000.0
	manaPenalty = -25.0
	#火焰和爆炸伤害减免比例
	# Default: 0.75
	# Range: 0.0 ~ 1.0
	damageReduction = 0.75
	#哥布林族体型缩放 1 为正常体型
	# Default: 0.5
	# Range: 0.1 ~ 10.0
	scale = 0.5

[titan]
	#攻击速度修改值
	# Default: -0.5
	# Range: -1.0 ~ 1.0
	attackSpeed = -0.5
	#攻击伤害修改值
	# Default: 0.5
	# Range: -1.0 ~ 5.0
	attackDamage = 0.5
	#最大生命值修改值
	# Default: 1.0
	# Range: -1.0 ~ 5.0
	maxHealth = 1.0
	#击退抗性
	# Default: 1.0
	# Range: 0.0 ~ 1.0
	knockbackResistance = 1.0
	#移动速度修改值
	# Default: 0.05
	# Range: -1.0 ~ 1.0
	movementSpeed = 0.05
	#跳跃力量修改值
	# Default: 0.75
	# Range: 0.0 ~ 2.0
	jumpStrength = 0.75
	#跨步高度值
	# Default: 1.4
	# Range: -1.0 ~ 3.0
	stepHeight = 1.4
	#交互距离修改值
	# Default: 1.0
	# Range: -1.0 ~ 3.0
	reachDistance = 1.0
	#魔力值修改量
	# Default: -50.0
	# Range: -10000.0 ~ 10000.0
	manaModifier = -50.0
	#水中下沉速度
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	waterSinkSpeed = 0.1
	#泰坦族体型缩放 1 为正常体型
	# Default: 3.0
	# Range: 0.1 ~ 10.0
	scale = 3.0

#结构战利品配置
#配置格式：物品ID,权重,最小数量,最大数量;多个物品用分号分隔
["Loot Settings"]
	#沙漠神殿战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	desertPyramidLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#丛林神庙战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	jungleTempleLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#废弃矿井战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	abandonedMineshaftLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#要塞图书馆战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	strongholdLibraryLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#林地府邸战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	woodlandMansionLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#村庄教堂战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageTempleLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#沉船宝藏配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	shipwreckTreasureLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#掠夺者前哨站配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	pillagerOutpostLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#埋藏宝藏配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	buriedTreasureLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#大型水下废墟配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	underwaterRuinBigLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#小型水下废墟配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	underwaterRuinSmallLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#雪屋地下室配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	iglooChestLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#堡垒遗迹-宝藏室配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	bastionTreasureLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#堡垒遗迹-桥梁配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	bastionBridgeLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#堡垒遗迹-居住区配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	bastionHousingLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#堡垒遗迹-杂项配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	bastionOtherLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#废弃传送门配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	ruinedPortalLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#末地城战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	endCityLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#远古城市配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	ancientCityLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#小型地牢配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	simpleDungeonLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#要塞走廊配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	strongholdCorridorLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#恐龙化石配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	fossilDinosaurLoot = ""
	#哺乳动物化石配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	fossilMammalLoot = ""
	#沉船补给配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	shipwreckSupplyLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#林地制图室配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	woodlandCartographyLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#要塞十字厅配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	strongholdCrossingLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#沉船地图配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	shipwreckMapLoot = "trinketsandbaubles:glowing_powder,10,1,2;trinketsandbaubles:glowing_ingot,1,1,1"
	#盔甲匠战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageArmorerLoot = ""
	#屠夫战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageButcherLoot = ""
	#制图师战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageCartographerLoot = ""
	#平原村庄房屋配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villagePlainsHouseLoot = ""
	#渔夫战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageFisherLoot = ""
	#制箭师战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageFletcherLoot = ""
	#制革厂战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageTanneryLoot = ""
	#村庄图书馆配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageLibraryLoot = ""
	#石匠战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageMasonLoot = ""
	#牧羊人战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageShepherdLoot = ""
	#工具匠战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageToolsmithLoot = ""
	#武器匠战利品配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageWeaponsmithLoot = ""
	#沙漠村庄房屋配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageDesertHouseLoot = ""
	#雪原村庄房屋配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageSnowyHouseLoot = ""
	#热带草原村庄房屋配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageSavannaHouseLoot = ""
	#针叶林村庄房屋配置
	#格式：物品ID,权重,最小数量,最大数量（用分号分隔）
	villageTaigaHouseLoot = ""
